name: Daily Standup Reminder

on:
  workflow_dispatch:  # Trigger manually from GitHub UI

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install discord.py

      - name: Run bot to send reminder
        run: python bot.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          THREAD_ID: ${{ secrets.THREAD_ID }}
